### ISSUE TITLE
Calendar Shifts: User Experience Improvement

### ISSUE THREAD

**Issue by shamystic** [GTHC/web#106]
Each shift should have not just the times which it has right now, but the users of the shift. These should be visible without having to click on the shift. To avoid clutter, this can be truncated to the first n users of the shift. Something like "4:00 PM - 4:30 PM: Shamikh, Aman, Vinit, ...". I also think this text should be in bold. The users are the key thing that is changing in the different shifts, so highlighting them is crucial. 
The shifts on the calendar should be different colors, they are currently all the same. After discussing with Vinit, just two colors is enough: a different color for the current user's shifts, and the blue for everyone else's shift is good. This makes it easy to differentiate what's important for the users.

**Comment by amanmibra** [comment]
@shamystic next time, iA, use the template that is given to you to make Issues and PRs
