### ISSUE TITLE
Frontend Fixes: login page scroll, phone number formatting, navbar clarity

### ISSUE THREAD

**Issue by shamystic** [GTHC/web#120]
**Describe the bug**
There are several front end issues that can be addressed to improve our app.
1. There is an unnecessary scrolling bar on the GTHC home page (before login). There is not enough content on the page to require a scroll bar, so this causes unnecessary clutter. This should be removed. 
![image](https://user-images.githubusercontent.com/7245697/72212611-1a182d00-34ad-11ea-9249-ca7411d84d7d.png)

2. Phone numbers are formatted incorrectly. Go to https://staging.gthc.io/app/team and view Team Table to observe this. We should be removing non-numeric characters from phone numbers before saving, and then use https://api.rubyonrails.org/classes/ActionView/Helpers/NumberHelper.html#method-i-number_to_phone to render phone numbers in the front end. 
![image](https://user-images.githubusercontent.com/7245697/72212646-cbb75e00-34ad-11ea-9236-c77ac9b03fcb.png)

3. From a user experience perspective, the purpose of different pages on the app should be immediately obvious even before thorough exploration. Right now, it is not immediately obvious what the difference is before "Home" and "Dashboard", until the user clicks on Dashboard and sees team specific information. For better clarity, we should name Dashboard to something like "Tent Dashboard" or "Team Dashboard". I asked Vinit if this was looked into during his user testing, but he said it did not come up. However, it was brought to my attention when testing with one of my friends recently. We want to make the purpose of the page obvious even before exploration, since the user may not always want to explore. 
![image](https://user-images.githubusercontent.com/7245697/72212647-d540c600-34ad-11ea-9087-d2019d615704.png)

4. We should replace the login with NetID blue button with the high res version. If the tern who was assigned this task doesn't want to do it, we should just take care of it ourselves, just lmk and I will do it. 

**To Reproduce**
1. Go to https://gthc.io/login and maximize your window. The scroll bar should go away, but it does not. 
2. Go to https://staging.gthc.io/app/team and view Team Table to view phone numbers.

**Comment by amanmibra** [comment]
@MoKhatami see number 4

**Comment by amanmibra** [comment]
@shamystic Just want to clarify before I try to get some of these fixes done, but you have started on the phone number formatting yourself?

**Comment by shamystic** [comment]
Yes, phone numbers are fixed
