### ISSUE TITLE
Availability UI

### ISSUE THREAD

**Issue by Vinitowinit** [GTHC/web#53]
**Is your feature request related to a problem? Please describe.**
When viewing the availability in login, User Profile, and Team Profile adjust the description to "Click icons below to select <strong> unavailability </strong>" in both the login and user profile section.

**Describe the solution you'd like**
The desired solution is adjusting description to "Click icons below to select <strong> unavailability </strong>" in both the login and user profile section

**To Reproduce**
<img width="1031" alt="screen shot 2019-01-06 at 1 51 18 pm" src="https://user-images.githubusercontent.com/29737830/50799880-d9327a80-1292-11e9-84c4-121d33481f41.png">

A
1. Go to the Login
2. Go to Availability Section
B
1. When logged in, go to User Profile
2. Go to Edit User Availability 
C
1. When logged in, go to Team Profile
2. Press on Availability in Team Table

**Comment by amanmibra** [comment]
Why did you reopen this @vinitbytheminute @Vinitowinit ?

**Comment by Vinitowinit** [comment]
Hey Aman, I reopened this because two days ago when checking out the staging branch to approve your PR, I realized the description for Availability component was off. Instead of saying "Click icons below to select unavailability " in both the login and user profile section..it said "Click icons below to select availability ". If you have addressed this already, then please close this issue. My wifi is unfortunately bad in the airport and I am having trouble running the staging branch.

**Comment by Vinitowinit** [comment]
@amanmibra Can you please change the wording from please "Click icons below to select availability " to "Click icons below to show when you are unavailable ". We need to change the instructions so that it matches with the new concept of having tenters input their unavailability for their week.

**Comment by amanmibra** [comment]
I don't think that change of wording is necessary. It already makes sense as it is. In fact your wording does not work at all, as you are not clicking the icons _just_ to select when you are unavailable, but when you are either "available", "somewhat available, or "not available".
