### ISSUE TITLE
Availibility Changes are Reseted 

### ISSUE THREAD

**Issue by Vinitowinit** [GTHC/web#54]
**Describe the bug**
During Log In, if user chooses to continue to the next/previous section and return to Availability, the values they entered disappears and resets. 

**To Reproduce**
1. Sign Up 
2. Click to Availability and Fill it out
3. Press Next or Back
4. Return to Availability and see Page Reseted

**Expected behavior**
If I were to go Next or Back and then return to Availability, I expect to see my availability filled out and still present.

**Screenshots**
Availability Page without my availability added
<img width="651" alt="screen shot 2019-01-04 at 11 45 22 am" src="https://user-images.githubusercontent.com/29737830/50708657-f872a300-1019-11e9-81ef-79c4a47a193f.png">

Availability Added
<img width="803" alt="screen shot 2019-01-04 at 12 10 33 pm" src="https://user-images.githubusercontent.com/29737830/50708674-07595580-101a-11e9-846c-46f278fb8705.png">
<img width="826" alt="screen shot 2019-01-04 at 12 10 56 pm" src="https://user-images.githubusercontent.com/29737830/50708682-0fb19080-101a-11e9-9c4f-6742ce5e7146.png">

Move to Back Page
<img width="856" alt="screen shot 2019-01-04 at 12 11 13 pm" src="https://user-images.githubusercontent.com/29737830/50708706-1fc97000-101a-11e9-9abb-9404219d2c10.png">

Move to Next Page
<img width="939" alt="screen shot 2019-01-04 at 12 11 35 pm" src="https://user-images.githubusercontent.com/29737830/50708714-248e2400-101a-11e9-8fad-0db08b0a4f93.png">

Back to Availability Page and availability reseted 

<img width="863" alt="screen shot 2019-01-04 at 12 11 26 pm" src="https://user-images.githubusercontent.com/29737830/50708753-53a49580-101a-11e9-9940-41b704f17bda.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amanmibra** [comment]
Bro this is not a bug, I told you to click feature request...

Logically does it make sense to choose bug report for this over a feature request???
